true_function: "mixed_log_linear"

assumed_function: "one_cyclic_power"

# "mixed_log_linear" or "one_cyclic_power"

function_names: ["mixed_log_linear", "one_cyclic_power", "two_cyclic_power"]

parameter_lists:
  N_MAX: &N_MAX 500
  N_TRIALS: 20
  GRID_RESOLUTION: &GRID_RESOLUTION 100

  # mixed log linear model
  params_mixed_log_linear:
    param_slope: 0.89 # 실제 데이터 범위에서 약간 넉넉한 정도 0.6~0.9, a,b, lambda 분포 그려보기
    param_intercept: 11.13
    param_log_mix: 0.22
    param_noise: 60 # only available in the likelihood function, 11개, 0.1 interval로...
  # given number  기준으로 플마 10%
  params_optimize_mixed_log_linear:
    param_slope_initial: 0.5
    param_slope_range_start: 0
    param_slope_range_end: 1

    param_intercept_initial: 0
    param_intercept_range_start: 0
    param_intercept_range_end: *N_MAX

    param_log_mix_initial: 0.5
    param_log_mix_range_start: 0.0
    param_log_mix_range_end: 1.0

    param_noise_initial: 50
    param_noise_range_start: 10
    param_noise_range_end: 100

  params_ADO_mixed_log_linear:
    grid_parameters:
      param_slope:
        type: arange
        start: 0
        end: 2
        num: 0.1

      param_intercept:
        type: linspace
        start: 0
        end: *N_MAX
        num: 10

      param_log_mix:
        type: linspace
        start: 0.0
        end: 1.0
        num: 10

      param_noise:
        type: linspace
        start: 1
        end: *N_MAX
        num: 10

  # one cyclic power model
  params_one_cyclic_power:
    param_exponent: 0.5
    param_noise: 84.7 # only in available in the likelihood function

  params_optimize_one_cyclic_power:
    param_exponent_initial: 1
    param_exponent_range_start: 0.01
    param_exponent_range_end: 5

    param_noise_initial: 50
    param_noise_range_start: 10
    param_noise_range_end: 100

  params_ADO_one_cyclic_power:
    grid_parameters:
      param_exponent:
        type: linspace
        start: 0.01
        end: 5
        num: 10
      param_noise:
        type: linspace
        start: 1
        end: *N_MAX
        num: 10

  # two cyclic power model
  params_two_cyclic_power:
    param_exponent: 1
    param_noise: 84.7 # only available in the likelihood function

  params_optimize_two_cyclic_power:
    param_exponent_initial: 1
    param_exponent_range_start: 0.01
    param_exponent_range_end: 5

    param_noise_initial: 50
    param_noise_range_start: 10
    param_noise_range_end: 100

  params_ADO_two_cyclic_power:
    grid_parameters:
      param_exponent:
        type: linspace
        start: 0.5
        end: 1.5
        num: 10
      param_noise:
        type: geomspace
        start: 1
        end: 30
        num: 10
