n_trials: 45
n_DVs: 2

GPR:
  n_kernels: 2
  alpha: 1e-10
  normalize_y: True
  n_restarts_optimizer: 0
  type_kernels_index: [0,6]
  parameters_list: [[1.0, 'fixed'],[1.0, 'fixed']]
  multiplied_indices: [[0], [1]]
  summed_indices: [[], []]
  gpr_random_state: None

GPAL:
  return_std: True
  return_cov: False
  save_results_dir: 'results'
  save_models_dir: 'models'




