## Arguments related to the experimental environment

num_trials: 20                      # Number of experiment trials for a subject.            
seed: null                           # A random seed value for reproducibility.
num_DVs: 1                          # The number of design variables subject to optimization.



## Arguments related to initializing the GPR instance.

normalize_y: True                 # A binary mask indicating whether to normalize the target values while fitting.
n_restarts_optimizer: 100          # The number of restarts of the optimizer to find the optimal kernel parameters.
kernel_types: [0,6,8]         # A list of indices of kernels to be combined. Refer to 'kernelTypeDic' above.
kernel_arguments: [[1.0], # A list of list of arguments to be fed to each kernel.
                   [1.0],
                   [0.05]]
combine_format: 'k1*k2+k3'
gpr_random_state: null            # A parameter determining random number generation in initializing the centers of the GP regressor.



## Arguments related to optimizing the GPR instance.

return_std: True                  # A binary mask indicating whether to return standard deviation of posterior distribution at each query value.
return_cov: False                 # A binary mask indicating whether to return covaraince matrix of posterior distribution at each query value.



## Arguments related to running an experiment.

save_results_dir: 'results'       # A directory to store the task results.
save_models_dir: 'models'         # A directory to store the trained Gaussian process regressor models.
save_figures_dir: 'figures'       # A directory to store the figures during analysis.



