[project]
name = "PACKAGE_NAME"
version = "0.1.0"

dependenceis = [
    "numpy==2.2.6",
    "matplotlib==3.10.3",
    "PyYAML==6.0.2",
    "pandas==2.3.1",
    "scipy==1.15.3",
    "scikit-learn"==1.7.1"
]